---
title: "Project_2"
output: html_notebook
---


#Load the dataset
```{r}
seeds = read.csv('seeds.csv')
seeds
```
#ViolinPlot
```{r}
#library(ggplot2)
ggplot(data = seeds, aes(x = as.factor(Type), y = Kernel.Length, fill = as.factor(Type))) +
  geom_violin() +
  labs(
    title = "Violinplot of Kernel Length by Type",
    x = "Type",
    y = "Kernel Length",
    caption = "Source: Iskulghar"
  )
    #theme_minimal()
```
```{r}
ggplot(data = seeds, aes(x = as.factor(Type), y = Kernel.Width, fill = as.factor(Type))) +
  geom_violin() +
  labs(
    title = "Violinplot of Kernel Width by Type",
    x = "Type",
    y = "Kernel Width",
    caption = "Source: Iskulghar"
  )
```
```{r}
ggplot(data = seeds, aes(x = as.factor(Type), y = Kernel.Groove, fill = as.factor(Type))) +
  geom_violin() +
  labs(
    title = "Violinplot of Kernel Groove by Type",
    x = "Type",
    y = "Kernel Groove",
    caption = "Source: Iskulghar"
  )
```
#Boxplot
```{r}
ggplot(data = seeds, aes(x = as.factor(Type), y = Kernel.Length, fill = as.factor(Type))) +
  geom_boxplot() +
  labs(
    title = "Boxplot of Kernel Length by Type",
    x = "Type",
    y = "Kernel Length",
    caption = "Source: Iskulghar"
  )
```
```{r}
ggplot(data = seeds, aes(x = as.factor(Type), y = Kernel.Width, fill = as.factor(Type))) +
  geom_boxplot() +
  labs(
    title = "Boxplot of Kernel widthth by Type",
    x = "Type",
    y = "Kernel widthth",
    caption = "Source: Iskulghar"
  )
```
```{r}
ggplot(data = seeds, aes(x = as.factor(Type), y = Kernel.Groove, fill = as.factor(Type))) +
  geom_boxplot() +
  labs(
    title = "Violinplot of Kernel Groove by Type",
    x = "Type",
    y = "Kernel Groove",
    caption = "Source: Iskulghar"
  )
```
#Interactive plot

```{r}
library(plotly)

fig = seeds %>%
  plot_ly(y = ~Kernel.Length, type = 'violin')
  
fig

```
```{r}
fig = seeds %>%
  plot_ly(y = ~Kernel.Width, type = 'violin')
  
fig
```


```{r}
fig = seeds %>%
  plot_ly(y = ~Perimeter, type = 'violin')
  
fig
```



```{r}
plot_ly(seeds, y = ~Kernel.Length, type = 'box')
```


```{r}
plot_ly(seeds, y = ~Kernel.Width, type = 'box')
```


```{r}
plot_ly(seeds, y = ~Perimeter, type = 'box')
```


```{r}
cor(seeds$Kernel.Length, seeds$Kernel.Width)
```

```{r}
cor(seeds$Kernel.Width, seeds$Kernel.Width)
```
```{r}
cor_matrix = cor(seeds[ ,1:7])
cor_matrix
```
```{r}
library(ggcorrplot)
ggcorrplot(cor_matrix)
```
```{r}
ggcorrplot(cor_matrix, type = "lower")
```

```{r}
ggcorrplot(cor_matrix, 
           type = "lower",
           colors = c("purple", "white", "red"),
           lab = TRUE)
```

```{r}
library(GGally)
pairs_plot= ggpairs(seeds, aes(colour = as.factor(Type)))+
  theme_grey(base_size = 14) +  # Adjust the base font size
  theme(axis.text = element_text(size = 18),  # Adjust axis text size
        axis.title = element_text(size = 20))
pairs_plot
# Adjust axis title size
```

```{r}
ggsave("pairs_plot_500dpi.png", plot=pairs_plot, height = 10, width = 15)
```


```{r}
library(stats)

seeds_pca = prcomp(seeds[ , -8], scale = TRUE, center = TRUE)
seeds_pca
```

```{r}
summary(seeds_pca)
```

```{r}
pc_12 = data.frame(seeds_pca$x[ , 1:3])
head(pc_12)
```

```{r}
pc_12_class = cbind(pc_12, Target = seeds$Type)
pc_12_class
```
# Bar plot of PCAs 

```{r}
library(factoextra)
fviz_eig(seeds_pca, xlab = "Principal Component", ylab = "Percentage of explained variance",addlabels = TRUE)
```
# Contribution plot of PCs (Circular plot)
```{r}
fviz_pca_var(seeds_pca,
             col.var = "contrib",gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)

```

# Contribution plot as Heatmap

```{r}
library("corrplot")
var = get_pca_var(seeds_pca)
corrplot(var$cos2)
```
# Cluster plot after PCA

```{r}
#seeds$Type_numeric = as.numeric(seeds$Type)+
fviz_pca_ind(seeds_pca,
             geom.ind  = "point",
             
             #Target = seeds$Type,
             col.ind = seeds$Type,
             addEllipses = TRUE)
```
#Clustering

```{r}
kmeans_result = kmeans(seeds[ , 1:7], centers = 3 )
kmeans_result
```
```{r}
library(cluster)
clusplot(seeds, kmeans_result$cluster)
```
#Classification

```{r}
library(lattice)
library(e1071)
library(caret)

train_ix = createDataPartition(seeds$Type, p = 0.8, list = FALSE)
train_data = seeds[train_ix, ]
test_data = seeds[-train_ix, ]

train_data
```

```{r}
test_data
```


```{r}
svm_model = svm(Type ~ Area+Perimeter+Compactness+Kernel.Length+Kernel.Width+Asymmetry.Coeff+Kernel.Groove, data = train_data, kernel = "linear")

test_data[24, -8]
```

```{r}
predict(svm_model, newdata = test_data[24,-8])
```


```{r}
# Generate predictions
predictions = predict(svm_model, newdata = test_data)

# Convert predictions to factor with levels of test_data$Type
predictions = factor(predictions, levels = levels(test_data$Type))

# Convert test_data$Type to factor if it's not already
test_data$Type <- factor(test_data$Type, levels = levels(predictions))

# Create confusion matrix
conf_matrix = confusionMatrix(predictions, test_data$Type)
conf_matrix
```



```{r}
cm = as.data.frame(conf_matrix$table)

ggplot(cm, aes(Prediction, Reference, fill = Freq)) + 
  geom_tile() +
  geom_text(aes(label = Freq)) + 
  scale_fill_gradient(low="purple", high="red")
```


#2. Using regression dataset 

```{r}
library(datasets)
admission = read.csv('US Admission.csv')
admission
```

# Remove the "Serial No" column
```{r}
admission = admission[, -1]
admission
```


#Plot linear regression 

```{r}
x = admission$Chance.of.Admit
y = admission$GRE.Score

plot(x, y)
```
```{r}
x = admission$Chance.of.Admit
y = admission$TOEFL.Score

plot(x, y)
```
```{r}
x = admission$Chance.of.Admit
y = admission$University.Rating

plot(x, y)
```
```{r}
x = admission$Chance.of.Admit
y = admission$SOP

plot(x, y)
```

```{r}
x = admission$Chance.of.Admit
y = admission$LOR

plot(x, y)
```
```{r}
x = admission$Chance.of.Admit
y = admission$CGPA

plot(x, y)
```
```{r}
x = admission$Chance.of.Admit
y = admission$Research

plot(x, y)
```
#Plot polynomial regression 

```{r}
ggplot(admission, aes(x =Chance.of.Admit , y=GRE.Score)) + 
  geom_point() +
  geom_smooth(method = "lm", formula = y~poly(x, 2), level = 0.95,)+
  ggtitle(paste("Polynomial Regression (Power 2) -", "GRE.Score vs Chance of Admit"))
```

```{r}
ggplot(admission, aes(x =Chance.of.Admit , y=TOEFL.Score
)) + 
  geom_point() +
  geom_smooth(method = "lm", formula = y~poly(x, 2), level = 0.9,)+
  ggtitle(paste("Polynomial Regression (Power 2) -", "TOEFL.Score vs Chance of Admit"))
```

```{r}
ggplot(admission, aes(x =Chance.of.Admit , y=University.Rating
)) + 
  geom_point() +
  geom_smooth(method = "lm", formula = y~poly(x, 2), level = 0.9,)
  #title(paste("Polynomial Regression (Power 2)-","Rating vs chance of admit"))
```

```{r}
ggplot(admission, aes(x =Chance.of.Admit , y=SOP
)) + 
  geom_point() +
  geom_smooth(method = "lm", formula = y~poly(x, 2), level = 0.9,)
```
```{r}
ggplot(admission, aes(x =Chance.of.Admit , y=LOR
)) + 
  geom_point() +
  geom_smooth(method = "lm", formula = y~poly(x, 2), level = 0.9,)
```
```{r}
ggplot(admission, aes(x =Chance.of.Admit , y=CGPA
)) + 
  geom_point() +
  geom_smooth(method = "lm", formula = y~poly(x, 2), level = 0.9,)

```

```{r}
ggplot(admission, aes(x =Chance.of.Admit , y=Research
)) + 
  geom_point() +
  geom_smooth(method = "lm", formula = y~poly(x, 2), level = 0.9,)
```
#Regression Model
```{r}

lm_model = lm(Chance.of.Admit ~GRE.Score+TOEFL.Score+University.Rating+SOP+LOR+CGPA+Research,data=admission)
summary(lm_model)
```


